name = "meshjs/swap"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'meshjs/swap'"

[repository]
user = "meshjs"
project = "swap"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.0.1-beta"
source = "github"
