name = "meshjs/marketplace"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'meshjs/marketplace'"

[repository]
user = "meshjs"
project = "marketplace"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.0.1-beta"
source = "github"