name: Documentation improvements
description: Suggest documentation improvements
#title: ""
labels: ["enhancement"]
#assignees:
#  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
        Please check the existing issues before submitting.
  - type: textarea
    id: description
    attributes:
      label: Describe the issue with the documentation
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Suggest a solution
      description: Describe how the documentation can be improved or corrected.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Would you be willing to implement it?
      options:
        - label: "Yes, I will implement it."