export const HARDENED_OFFSET = 0x80000000;

export const DEFAULT_ACCOUNT_KEY_DERIVATION_PATH = [
  1852 + HARDENED_OFFSET,
  1815 + HARDENED_OFFSET,
  0 + HARDENED_OFFSET,
];

export const DEFAULT_PAYMENT_KEY_DERIVATION_PATH = [
  ...DEFAULT_ACCOUNT_KEY_DERIVATION_PATH,
  0,
];
export const DEFAULT_STAKE_KEY_DERIVATION_PATH = [
  ...DEFAULT_ACCOUNT_KEY_DERIVATION_PATH,
  2,
];
export const DEFAULT_DREP_KEY_DERIVATION_PATH = [
  ...DEFAULT_ACCOUNT_KEY_DERIVATION_PATH,
  3,
];
