name = "fabianbormann/payment-splitter"
version = "0.1.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'fabianbormann/payment-splitter'"

[repository]
user = "fabianbormann"
project = "payment-splitter"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
